[package]
name = "audio-metadata"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
symphonia = { version = "0.5.5", features = ["mp3", "aac", "flac", "isomp4", "ogg", "vorbis", "wav", "aiff"] }
thiserror.workspace = true
uuid.workspace = true
